setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
  index.number_of_replicas: 0

setup.kibana:
  host: "${KIBANA_HOST:kibana:5601}"

output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOSTS:elasticsearch:9200}"]

logging.json: true
logging.metrics.enabled: false

filebeat.prospectors:
  - type: log
    paths:
     - '/var/lib/docker/containers/*/*.log'
    json.message_key: log
    json.overwrite_keys: true
    json.keys_under_root: false
    json.add_error_key: true
